<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1,'code' => 'AF' ,'name' => "Afghanistan"),
            array('id' => 2,'code' => 'AL' ,'name' => "Albania"),
            array('id' => 3,'code' => 'DZ' ,'name' => "Algeria"),
            array('id' => 4,'code' => 'AS' ,'name' => "American Samoa"),
            array('id' => 5,'code' => 'AD' ,'name' => "Andorra"),
            array('id' => 6,'code' => 'AO' ,'name' => "Angola"),
            array('id' => 7,'code' => 'AI' ,'name' => "Anguilla"),
            array('id' => 8,'code' => 'AQ' ,'name' => "Antarctica"),
            array('id' => 9,'code' => 'AG' ,'name' => "Antigua And Barbuda"),
            array('id' => 10,'code' => 'AR','name' => "Argentina"),
            array('id' => 11,'code' => 'AM','name' => "Armenia"),
            array('id' => 12,'code' => 'AW','name' => "Aruba"),
            array('id' => 13,'code' => 'AU','name' => "Australia"),
            array('id' => 14,'code' => 'AT','name' => "Austria"),
            array('id' => 15,'code' => 'AZ','name' => "Azerbaijan"),
            array('id' => 16,'code' => 'BS','name' => "Bahamas The"),
            array('id' => 17,'code' => 'BH','name' => "Bahrain"),
            array('id' => 18,'code' => 'BD','name' => "Bangladesh"),
            array('id' => 19,'code' => 'BB','name' => "Barbados"),
            array('id' => 20,'code' => 'BY','name' => "Belarus"),
            array('id' => 21,'code' => 'BE','name' => "Belgium"),
            array('id' => 22,'code' => 'BZ','name' => "Belize"),
            array('id' => 23,'code' => 'BJ','name' => "Benin"),
            array('id' => 24,'code' => 'BM','name' => "Bermuda"),
            array('id' => 25,'code' => 'BT','name' => "Bhutan"),
            array('id' => 26,'code' => 'BO','name' => "Bolivia"),
            array('id' => 27,'code' => 'BA','name' => "Bosnia and Herzegovina"),
            array('id' => 28,'code' => 'BW','name' => "Botswana"),
            array('id' => 29,'code' => 'BV','name' => "Bouvet Island"),
            array('id' => 30,'code' => 'BR','name' => "Brazil"),
            array('id' => 31,'code' => 'IO','name' => "British Indian Ocean Territory"),
            array('id' => 32,'code' => 'BN','name' => "Brunei"),
            array('id' => 33,'code' => 'BG','name' => "Bulgaria"),
            array('id' => 34,'code' => 'BF','name' => "Burkina Faso"),
            array('id' => 35,'code' => 'BI','name' => "Burundi"),
            array('id' => 36,'code' => 'KH','name' => "Cambodia"),
            array('id' => 37,'code' => 'CM','name' => "Cameroon"),
            array('id' => 38,'code' => 'CA','name' => "Canada"),
            array('id' => 39,'code' => 'CV','name' => "Cape Verde"),
            array('id' => 40,'code' => 'KY','name' => "Cayman Islands"),
            array('id' => 41,'code' => 'CF','name' => "Central African Republic"),
            array('id' => 42,'code' => 'TD','name' => "Chad"),
            array('id' => 43,'code' => 'CL','name' => "Chile"),
            array('id' => 44,'code' => 'CN','name' => "China"),
            array('id' => 45,'code' => 'CX','name' => "Christmas Island"),
            array('id' => 46,'code' => 'CC','name' => "Cocos (Keeling) Islands"),
            array('id' => 47,'code' => 'CO','name' => "Colombia"),
            array('id' => 48,'code' => 'KM','name' => "Comoros"),
            array('id' => 49,'code' => 'CG','name' => "Congo"),
            array('id' => 50,'code' => 'CD','name' => "Congo The Democratic Republic Of The"),
            array('id' => 51,'code' => 'CK','name' => "Cook Islands"),
            array('id' => 52,'code' => 'CR','name' => "Costa Rica"),
            array('id' => 53,'code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)"),
            array('id' => 54,'code' => 'HR','name' => "Croatia (Hrvatska)"),
            array('id' => 55,'code' => 'CU','name' => "Cuba"),
            array('id' => 56,'code' => 'CY','name' => "Cyprus"),
            array('id' => 57,'code' => 'CZ','name' => "Czech Republic"),
            array('id' => 58,'code' => 'DK','name' => "Denmark"),
            array('id' => 59,'code' => 'DJ','name' => "Djibouti"),
            array('id' => 60,'code' => 'DM','name' => "Dominica"),
            array('id' => 61,'code' => 'DO','name' => "Dominican Republic"),
            array('id' => 62,'code' => 'TP','name' => "East Timor"),
            array('id' => 63,'code' => 'EC','name' => "Ecuador"),
            array('id' => 64,'code' => 'EG','name' => "Egypt"),
            array('id' => 65,'code' => 'SV','name' => "El Salvador"),
            array('id' => 66,'code' => 'GQ','name' => "Equatorial Guinea"),
            array('id' => 67,'code' => 'ER','name' => "Eritrea"),
            array('id' => 68,'code' => 'EE','name' => "Estonia"),
            array('id' => 69,'code' => 'ET','name' => "Ethiopia"),
            array('id' => 70,'code' => 'XA','name' => "External Territories of Australia"),
            array('id' => 71,'code' => 'FK','name' => "Falkland Islands"),
            array('id' => 72,'code' => 'FO','name' => "Faroe Islands"),
            array('id' => 73,'code' => 'FJ','name' => "Fiji Islands"),
            array('id' => 74,'code' => 'FI','name' => "Finland"),
            array('id' => 75,'code' => 'FR','name' => "France"),
            array('id' => 76,'code' => 'GF','name' => "French Guiana"),
            array('id' => 77,'code' => 'PF','name' => "French Polynesia"),
            array('id' => 78,'code' => 'TF','name' => "French Southern Territories"),
            array('id' => 79,'code' => 'GA','name' => "Gabon"),
            array('id' => 80,'code' => 'GM','name' => "Gambia The"),
            array('id' => 81,'code' => 'GE','name' => "Georgia"),
            array('id' => 82,'code' => 'DE','name' => "Germany"),
            array('id' => 83,'code' => 'GH','name' => "Ghana"),
            array('id' => 84,'code' => 'GI','name' => "Gibraltar"),
            array('id' => 85,'code' => 'GR','name' => "Greece"),
            array('id' => 86,'code' => 'GL','name' => "Greenland"),
            array('id' => 87,'code' => 'GD','name' => "Grenada"),
            array('id' => 88,'code' => 'GP','name' => "Guadeloupe"),
            array('id' => 89,'code' => 'GU','name' => "Guam"),
            array('id' => 90,'code' => 'GT','name' => "Guatemala"),
            array('id' => 91,'code' => 'XU','name' => "Guernsey and Alderney"),
            array('id' => 92,'code' => 'GN','name' => "Guinea"),
            array('id' => 93,'code' => 'GW','name' => "Guinea-Bissau"),
            array('id' => 94,'code' => 'GY','name' => "Guyana"),
            array('id' => 95,'code' => 'HT','name' => "Haiti"),
            array('id' => 96,'code' => 'HM','name' => "Heard and McDonald Islands"),
            array('id' => 97,'code' => 'HN','name' => "Honduras"),
            array('id' => 98,'code' => 'HK','name' => "Hong Kong S.A.R."),
            array('id' => 99,'code' => 'HU','name' => "Hungary"),
            array('id' => 100,'code' => 'IS','name' => "Iceland"),
            array('id' => 101,'code' => 'IN','name' => "India"),
            array('id' => 102,'code' => 'ID','name' => "Indonesia"),
            array('id' => 103,'code' => 'IR','name' => "Iran"),
            array('id' => 104,'code' => 'IQ','name' => "Iraq"),
            array('id' => 105,'code' => 'IE','name' => "Ireland"),
            array('id' => 106,'code' => 'IL','name' => "Israel"),
            array('id' => 107,'code' => 'IT','name' => "Italy"),
            array('id' => 108,'code' => 'JM','name' => "Jamaica"),
            array('id' => 109,'code' => 'JP','name' => "Japan"),
            array('id' => 110,'code' => 'XJ','name' => "Jersey"),
            array('id' => 111,'code' => 'JO','name' => "Jordan"),
            array('id' => 112,'code' => 'KZ','name' => "Kazakhstan"),
            array('id' => 113,'code' => 'KE','name' => "Kenya"),
            array('id' => 114,'code' => 'KI','name' => "Kiribati"),
            array('id' => 115,'code' => 'KP','name' => "Korea North"),
            array('id' => 116,'code' => 'KR','name' => "Korea South"),
            array('id' => 117,'code' => 'KW','name' => "Kuwait"),
            array('id' => 118,'code' => 'KG','name' => "Kyrgyzstan"),
            array('id' => 119,'code' => 'LA','name' => "Laos"),
            array('id' => 120,'code' => 'LV','name' => "Latvia"),
            array('id' => 121,'code' => 'LB','name' => "Lebanon"),
            array('id' => 122,'code' => 'LS','name' => "Lesotho"),
            array('id' => 123,'code' => 'LR','name' => "Liberia"),
            array('id' => 124,'code' => 'LY','name' => "Libya"),
            array('id' => 125,'code' => 'LI','name' => "Liechtenstein"),
            array('id' => 126,'code' => 'LT','name' => "Lithuania"),
            array('id' => 127,'code' => 'LU','name' => "Luxembourg"),
            array('id' => 128,'code' => 'MO','name' => "Macau S.A.R."),
            array('id' => 129,'code' => 'MK','name' => "Macedonia"),
            array('id' => 130,'code' => 'MG','name' => "Madagascar"),
            array('id' => 131,'code' => 'MW','name' => "Malawi"),
            array('id' => 132,'code' => 'MY','name' => "Malaysia"),
            array('id' => 133,'code' => 'MV','name' => "Maldives"),
            array('id' => 134,'code' => 'ML','name' => "Mali"),
            array('id' => 135,'code' => 'MT','name' => "Malta"),
            array('id' => 136,'code' => 'XM','name' => "Man (Isle of)"),
            array('id' => 137,'code' => 'MH','name' => "Marshall Islands"),
            array('id' => 138,'code' => 'MQ','name' => "Martinique"),
            array('id' => 139,'code' => 'MR','name' => "Mauritania"),
            array('id' => 140,'code' => 'MU','name' => "Mauritius"),
            array('id' => 141,'code' => 'YT','name' => "Mayotte"),
            array('id' => 142,'code' => 'MX','name' => "Mexico"),
            array('id' => 143,'code' => 'FM','name' => "Micronesia"),
            array('id' => 144,'code' => 'MD','name' => "Moldova"),
            array('id' => 145,'code' => 'MC','name' => "Monaco"),
            array('id' => 146,'code' => 'MN','name' => "Mongolia"),
            array('id' => 147,'code' => 'MS','name' => "Montserrat"),
            array('id' => 148,'code' => 'MA','name' => "Morocco"),
            array('id' => 149,'code' => 'MZ','name' => "Mozambique"),
            array('id' => 150,'code' => 'MM','name' => "Myanmar"),
            array('id' => 151,'code' => 'NA','name' => "Namibia"),
            array('id' => 152,'code' => 'NR','name' => "Nauru"),
            array('id' => 153,'code' => 'NP','name' => "Nepal"),
            array('id' => 154,'code' => 'AN','name' => "Netherlands Antilles"),
            array('id' => 155,'code' => 'NL','name' => "Netherlands The"),
            array('id' => 156,'code' => 'NC','name' => "New Caledonia"),
            array('id' => 157,'code' => 'NZ','name' => "New Zealand"),
            array('id' => 158,'code' => 'NI','name' => "Nicaragua"),
            array('id' => 159,'code' => 'NE','name' => "Niger"),
            array('id' => 160,'code' => 'NG','name' => "Nigeria"),
            array('id' => 161,'code' => 'NU','name' => "Niue"),
            array('id' => 162,'code' => 'NF','name' => "Norfolk Island"),
            array('id' => 163,'code' => 'MP','name' => "Northern Mariana Islands"),
            array('id' => 164,'code' => 'NO','name' => "Norway"),
            array('id' => 165,'code' => 'OM','name' => "Oman"),
            array('id' => 166,'code' => 'PK','name' => "Pakistan"),
            array('id' => 167,'code' => 'PW','name' => "Palau"),
            array('id' => 168,'code' => 'PS','name' => "Palestinian Territory Occupied"),
            array('id' => 169,'code' => 'PA','name' => "Panama"),
            array('id' => 170,'code' => 'PG','name' => "Papua new Guinea"),
            array('id' => 171,'code' => 'PY','name' => "Paraguay"),
            array('id' => 172,'code' => 'PE','name' => "Peru"),
            array('id' => 173,'code' => 'PH','name' => "Philippines"),
            array('id' => 174,'code' => 'PN','name' => "Pitcairn Island"),
            array('id' => 175,'code' => 'PL','name' => "Poland"),
            array('id' => 176,'code' => 'PT','name' => "Portugal"),
            array('id' => 177,'code' => 'PR','name' => "Puerto Rico"),
            array('id' => 178,'code' => 'QA','name' => "Qatar"),
            array('id' => 179,'code' => 'RE','name' => "Reunion"),
            array('id' => 180,'code' => 'RO','name' => "Romania"),
            array('id' => 181,'code' => 'RU','name' => "Russia"),
            array('id' => 182,'code' => 'RW','name' => "Rwanda"),
            array('id' => 183,'code' => 'SH','name' => "Saint Helena"),
            array('id' => 184,'code' => 'KN','name' => "Saint Kitts And Nevis"),
            array('id' => 185,'code' => 'LC','name' => "Saint Lucia"),
            array('id' => 186,'code' => 'PM','name' => "Saint Pierre and Miquelon"),
            array('id' => 187,'code' => 'VC','name' => "Saint Vincent And The Grenadines"),
            array('id' => 188,'code' => 'WS','name' => "Samoa"),
            array('id' => 189,'code' => 'SM','name' => "San Marino"),
            array('id' => 190,'code' => 'ST','name' => "Sao Tome and Principe"),
            array('id' => 191,'code' => 'SA','name' => "Saudi Arabia"),
            array('id' => 192,'code' => 'SN','name' => "Senegal"),
            array('id' => 193,'code' => 'RS','name' => "Serbia"),
            array('id' => 194,'code' => 'SC','name' => "Seychelles"),
            array('id' => 195,'code' => 'SL','name' => "Sierra Leone"),
            array('id' => 196,'code' => 'SG','name' => "Singapore"),
            array('id' => 197,'code' => 'SK','name' => "Slovakia"),
            array('id' => 198,'code' => 'SI','name' => "Slovenia"),
            array('id' => 199,'code' => 'XG','name' => "Smaller Territories of the UK"),
            array('id' => 200,'code' => 'SB','name' => "Solomon Islands"),
            array('id' => 201,'code' => 'SO','name' => "Somalia"),
            array('id' => 202,'code' => 'ZA','name' => "South Africa"),
            array('id' => 203,'code' => 'GS','name' => "South Georgia"),
            array('id' => 204,'code' => 'SS','name' => "South Sudan"),
            array('id' => 205,'code' => 'ES','name' => "Spain"),
            array('id' => 206,'code' => 'LK','name' => "Sri Lanka"),
            array('id' => 207,'code' => 'SD','name' => "Sudan"),
            array('id' => 208,'code' => 'SR','name' => "Suriname"),
            array('id' => 209,'code' => 'SJ','name' => "Svalbard And Jan Mayen Islands"),
            array('id' => 210,'code' => 'SZ','name' => "Swaziland"),
            array('id' => 211,'code' => 'SE','name' => "Sweden"),
            array('id' => 212,'code' => 'CH','name' => "Switzerland"),
            array('id' => 213,'code' => 'SY','name' => "Syria"),
            array('id' => 214,'code' => 'TW','name' => "Taiwan"),
            array('id' => 215,'code' => 'TJ','name' => "Tajikistan"),
            array('id' => 216,'code' => 'TZ','name' => "Tanzania"),
            array('id' => 217,'code' => 'TH','name' => "Thailand"),
            array('id' => 218,'code' => 'TG','name' => "Togo"),
            array('id' => 219,'code' => 'TK','name' => "Tokelau"),
            array('id' => 220,'code' => 'TO','name' => "Tonga"),
            array('id' => 221,'code' => 'TT','name' => "Trinidad And Tobago"),
            array('id' => 222,'code' => 'TN','name' => "Tunisia"),
            array('id' => 223,'code' => 'TR','name' => "Turkey"),
            array('id' => 224,'code' => 'TM','name' => "Turkmenistan"),
            array('id' => 225,'code' => 'TC','name' => "Turks And Caicos Islands"),
            array('id' => 226,'code' => 'TV','name' => "Tuvalu"),
            array('id' => 227,'code' => 'UG','name' => "Uganda"),
            array('id' => 228,'code' => 'UA','name' => "Ukraine"),
            array('id' => 229,'code' => 'AE','name' => "United Arab Emirates"),
            array('id' => 230,'code' => 'GB','name' => "United Kingdom"),
            array('id' => 231,'code' => 'US','name' => "United States"),
            array('id' => 232,'code' => 'UM','name' => "United States Minor Outlying Islands"),
            array('id' => 233,'code' => 'UY','name' => "Uruguay"),
            array('id' => 234,'code' => 'UZ','name' => "Uzbekistan"),
            array('id' => 235,'code' => 'VU','name' => "Vanuatu"),
            array('id' => 236,'code' => 'VA','name' => "Vatican City State (Holy See)"),
            array('id' => 237,'code' => 'VE','name' => "Venezuela"),
            array('id' => 238,'code' => 'VN','name' => "Vietnam"),
            array('id' => 239,'code' => 'VG','name' => "Virgin Islands (British)"),
            array('id' => 240,'code' => 'VI','name' => "Virgin Islands (US)"),
            array('id' => 241,'code' => 'WF','name' => "Wallis And Futuna Islands"),
            array('id' => 242,'code' => 'EH','name' => "Western Sahara"),
            array('id' => 243,'code' => 'YE','name' => "Yemen"),
            array('id' => 244,'code' => 'YU','name' => "Yugoslavia"),
            array('id' => 245,'code' => 'ZM','name' => "Zambia"),
            array('id' => 246,'code' => 'ZW','name' => "Zimbabwe"),
            );
            DB::table('countries')->insert($countries);
        
    }
}
